model = "gpt-5.4"
model_reasoning_effort = "high"
personality = "pragmatic"

[mcp_servers.playwright]
args = [ "@playwright/mcp@latest" ]
command = "npx"

[mcp_servers.pencil]
command = "/Users/liuwei/.pencil/mcp/antigravity/out/mcp-server-darwin-arm64"
args = [ "--app", "antigravity" ]

[features]
multi_agent = true

[plugins."build-ios-apps@openai-curated"]
enabled = true

[projects."/Users/liuwei/go/src/vibelive"]
trust_level = "trusted"

[projects."/Users/liuwei/go/src/dreamtown/dream-town"]
trust_level = "trusted"

[projects."/Users/liuwei/go/src/runway"]
trust_level = "trusted"

[marketplaces.openai-bundled]
last_updated = "2026-04-17T04:25:58Z"
source_type = "local"
source = "/Users/liuwei/.codex/.tmp/bundled-marketplaces/openai-bundled"
